apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/apicurito.apicurio-designer: ""
  name: apicurito
spec:
  channel: latest
  installPlanApproval: Automatic
  name: apicurito
  source: community-operators
  sourceNamespace: openshift-marketplace
