kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: microcks
  labels:
    app: microcks
    app.kubernetes.io/instance: microcks
    container: spring
    group: microcks
spec:
  to:
    kind: Service
    name: microcks
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: spring
