kind: Keycloak
apiVersion: k8s.keycloak.org/v2alpha1
metadata:
  name: keycloak
  labels:
    app: keycloak
  namespace: keycloak
spec:
  instances: 1
  hostname:
    hostname: "keycloak.{{ .Values.clusterRouterDomain }}"
  http:
    tlsSecret: keycloak-tls
  db:
    vendor: postgres
    host: keycloak-db-postgresql
    port: 5432
    database: keycloak
    usernameSecret:
      name: keycloak-db-credentials
      key: username
    passwordSecret:
      name: keycloak-db-credentials
      key: password