kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
data:
  app-config-rhdh.yaml: |
    app:
      title: Contract-First IDP
      baseUrl: "https://backstage-backstage-developer-hub.{{ .Values.clusterRouterDomain }}"
    backend:
      auth:
        keys:
          - secret: ${BACKEND_SECRET}
      baseUrl: "https://backstage-backstage-developer-hub.{{ .Values.clusterRouterDomain }}"
      cors:
        origin: "https://backstage-backstage-developer-hub.{{ .Values.clusterRouterDomain }}"