clusterRouterDomain: apps.example.cluster.com
keycloak:
  backstageRealm:
    name: backstage
    displayName: backstage
  backstageClient:
    id: backstage
    secret: my-secret
  database:
    username: postgres
    password: my-database-password