apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: hawtio-operator
  namespace: hawtio-operator
spec:
  channel: stable-v1
  name: hawtio-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace