apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apicurito
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: "{{ .Values.gitHost }}/{{ .Values.gitOrg }}/platform-components.git"
    path: charts/apicurito
    targetRevision: "{{ .Values.gitRef }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: apicurio-designer
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
