apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: "{{ .Values.gitOrg }}/platform-components.git"
    path: developer-hub-helm
    targetRevision: "{{ .Values.gitRef }}"
    helm:
      parameters:
        - name: "clusterRouterDomain"
          value: "apps.{{ .Values.clusterBaseUrl }}"
        - name: "auth.sessionSecret"
          value: Q72XbDKY8IcNSNzAQjVwa3xmh4lfdvzG
        - name: "auth.keycloakUrl"
          value: "https://keycloak-keycloak.apps.{{ .Values.clusterBaseUrl }}"
        - name: "auth.keycloakRealm"
          value: backstage
        - name: "auth.clientId"
          value: backstage
        - name: "auth.clientSecret"
          value: "my-secret"
  destination:
    server: https://kubernetes.default.svc
    namespace: developer-hub
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    retry:
      limit: 0
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
