apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-domain
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: "{{ .Values.gitHost }}/{{ .Values.gitOrg }}/demo-domain.git"
    path: argoapps
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
